version: "3.9"

services:
  client:
    image: client
    build:
      context: ./client
    working_dir: /app
    command: npm start
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3401
    ports:
      - "3401:3401"

  server:
    image: server
    build:
      context: ./server
    working_dir: /app
    command: npm run api-dev
    volumes:
      - ./server:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development
    ports:
      - "3400:3000"

