version: "3.9"

services:
  client:
    image: client
    build:
      context: ./client
    working_dir: /app
    command: npm start
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3401
      - REACT_APP_API_URL=http://localhost:3400
    ports:
      - "3401:3401"

  client-build:
    image: client
    build:
      context: ./client
    working_dir: /app
    command: npm run build
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    profiles: [ci]

  server:
    image: server
    build:
      context: ./server
    working_dir: /app
    command: npm run api-dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4318/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=service.name=calendar-server,env=docker-compose
    ports:
      - "3400:3000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      LOG_LEVEL: debug

  #prometheus:
  #  image: prom/prometheus:latest
  #  container_name: prometheus
  #  ports:
  #    - "9090:9090"

