version: "3.9"

x-service-base: &api-base
  image: calendar-api
  build:
    context: ./api
    target: development
  environment:
    RAILS_ENV: assetbuild
    DATABASE_HOST: main-db
    DATABASE_NAME: calendar
    DATABASE_USERNAME: calendar
    DATABASE_PASSWORD: calendar
    SOURCE_PATH: $PWD
    LOG_LEVEL: DEBUG
  entrypoint: ""
  depends_on:
    - main-db
  volumes:
    - ./api:/app
    - vendor_bundle:/app/vendor/bundle
    - node_modules:/app/node_modules

services:
  client:
    image: client
    build:
      context: ./client
    working_dir: /app
    command: npm start
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3410
      - REACT_APP_API_URL=http://localhost:3402
    ports:
      - "3410:3410"

  client-build:
    image: client
    build:
      context: ./client
    working_dir: /app
    command: npm run build
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    profiles: [ci]

  main-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar
      POSTGRES_DB: calendar
    volumes:
      - main_db:/var/lib/postgresql/data
    ports:
      - "5532:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16687:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      LOG_LEVEL: debug

  server:
    image: server
    depends_on: [main-db]
    build:
      context: ./app
    working_dir: /app
    command: sh -c "/wait && pnpm run api-dev"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_RESOURCE_ATTRIBUTES=service.name: calendar-server,env=docker-compose
      DATABASE_URL: "postgresql://calendar:calendar@main-db:5432/calendar?schema=public"
      WAIT_HOSTS: main-db:5432
    ports:
      - "3402:3000"

  pnpm-install:
    profiles:
      - development
    image: server
    depends_on: [main-db]
    build:
      context: ./app
    working_dir: /app
    command: sh -c "/wait && pnpm install"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_RESOURCE_ATTRIBUTES=service.name: calendar-server,env=docker-compose
      DATABASE_URL: "postgresql://calendar:calendar@main-db:5432/calendar?schema=public"
      WAIT_HOSTS: main-db:5432

  api:
    <<: *api-base
    build:
      context: ./api
      target: assetbuild
    command: "bundle exec rails s -b 0.0.0.0"
    ports:
      - "3403:3000"

  db-migrate:
    <<: *api-base
    command: "bundle exec rails db:migrate db:seed"

  #prometheus:
  #  image: prom/prometheus:latest
  #  container_name: prometheus
  #  ports:
  #    - "9090:9090"

volumes:
  main_db:
  vendor_bundle:
  node_modules:
  client_node_modules:
