defaults: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

development:
  <<: *default

ci:
  <<: *default
  database: calendar_ci

test:
  <<: *default
  database: calendar_test

beta:
  <<: *default
  database: calendar_beta

production:
  <<: *default
