name: BE deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./calendar

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: calendar
          POSTGRES_PASSWORD: calendar
          POSTGRES_DB: calendar
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install -r requirements.txt
        working-directory: ./calendar/deploy

      - name: Run Ansible script
        run: ansible-playbook deploy.yml --extra-vars "db_password=${{ secrets.DB_PASSWORD }} db_host=${{ secrets.DB_HOST }} db_port=${{ secrets.DB_PORT }} db_name=calendar_app db_user=${{ secrets.DB_USER }}"
        working-directory: ./calendar/deploy
