name: BE deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./calendar

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install -r requirements.txt
        working-directory: ./calendar/deploy

      - name: Run Ansible script
        run: ansible-playbook deploy.yml --extra-vars "db_password=${{ secrets.DB_PASSWORD }} db_host=${{ secrets.DB_HOST }} db_port=${{ secrets.DB_PORT }} db_name=calendar_app db_user=${{ secrets.DB_USER }}"
        working-directory: ./calendar/deploy
